//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS_WebParts.GorevSemasiWP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class GorevSemasiWP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "17.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(GorevSemasiWP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "17.0.0.0")]
        private void @__BuildControlTree(global::IKYS_WebParts.GorevSemasiWP.GorevSemasiWP @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<link rel=\"stylesheet\" href=\"/Style%20Library/tskgv/css/Treant.css\">\r\n\r\n<style>" +
                        "\r\n    body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, fiel" +
                        "dset, input, textarea, p, blockquote, th, td {\r\n        margin: 0;\r\n        padd" +
                        "ing: 0;\r\n    }\r\n\r\n    table {\r\n        border-collapse: collapse;\r\n        borde" +
                        "r-spacing: 0;\r\n    }\r\n\r\n    fieldset, img {\r\n        border: 0;\r\n    }\r\n\r\n    ad" +
                        "dress, caption, cite, code, dfn, em, strong, th, var {\r\n        font-style: norm" +
                        "al;\r\n        font-weight: normal;\r\n    }\r\n\r\n    caption, th {\r\n        text-alig" +
                        "n: left;\r\n    }\r\n\r\n    h1, h2, h3, h4, h5, h6 {\r\n        font-size: 100%;\r\n     " +
                        "   font-weight: normal;\r\n    }\r\n\r\n    q:before, q:after {\r\n        content: \'\';\r" +
                        "\n    }\r\n\r\n    abbr, acronym {\r\n        border: 0;\r\n    }\r\n\r\n    body {\r\n        " +
                        "background: #fff;\r\n    }\r\n    /* optional Container STYLES */\r\n    .chart {\r\n   " +
                        "     min-height: 600px;\r\n        margin: 5px;\r\n        min-width: 1000px;\r\n    }" +
                        "\r\n\r\n    .Treant > .node {\r\n    }\r\n\r\n    .Treant > p {\r\n        font-family: \"Hel" +
                        "veticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"" +
                        "Lucida Grande\", sans-serif;\r\n        font-weight: bold;\r\n        font-size: 12px" +
                        ";\r\n    }\r\n\r\n    .node-name {\r\n        font-weight: bold;\r\n    }\r\n\r\n    .nodeExam" +
                        "ple1 {\r\n        padding: 2px;\r\n        -webkit-border-radius: 3px;\r\n        -moz" +
                        "-border-radius: 3px;\r\n        border-radius: 3px;\r\n        background-color: #ff" +
                        "ffff;\r\n        border: 1px solid #000;\r\n        width: 200px;\r\n        height: 7" +
                        "0px;\r\n        font-family: Tahoma;\r\n        font-size: 11px;\r\n    }\r\n    .nodeEx" +
                        "ample2 {\r\n        padding: 2px;\r\n        -webkit-border-radius: 3px;\r\n        -m" +
                        "oz-border-radius: 3px;\r\n        border-radius: 3px;\r\n        background-color: #" +
                        "d3d3d3;\r\n\r\n        border: 2px dashed #808080;\r\n        width: 200px;\r\n        h" +
                        "eight: 70px;\r\n        font-family: Tahoma;\r\n        font-size: 11px;\r\n    }\r\n   " +
                        " .nodeExample1 img {\r\n        margin-right: 10px;\r\n        max-height: 65px;\r\n  " +
                        "      max-width: 60px;\r\n    }\r\n</style>\r\n\r\n\r\n\r\n<script src=\"/Style%20Library/tsk" +
                        "gv/js/raphael.js\"></script>\r\n<script src=\"/Style%20Library/tskgv/js/Treant.js\"><" +
                        "/script>\r\n\r\n\r\n<div class=\"chart\" id=\"GorevSemasiDiv\"></div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "17.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "17.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "17.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
