//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBYS_WebParts.DuzenliNakitBagisciListesiWP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class DuzenliNakitBagisciListesiWP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton CloseBtn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlAnchor YonergeLnk;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.Label TitleLbl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.Label IdLbl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl CardHeader;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList AyDDL;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList YilDDL;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList DurumDDL;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText paramNakitBagisciIdLbl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.UpdateProgress updateProgress;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.Label BagisciAdiLbl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton ModalDoldurBtn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.Table BagisciTable;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.Label BagisBilgileriLbl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton ArmaganOlusturBtn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnNakitBagisciId;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnDuzenliBagisciId;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "18.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DuzenliNakitBagisciListesiWP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlCloseBtn() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.CloseBtn = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "CloseBtn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "close");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&times;"));
            @__ctrl.Click -= new System.EventHandler(this.CloseBtn_Click);
            @__ctrl.Click += new System.EventHandler(this.CloseBtn_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlYonergeLnk() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.YonergeLnk = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", " btn btn-outline-primary float-end me-4");
            @__ctrl.ID = "YonergeLnk";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-fancybox", "");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-type", "pdf");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-width", "960");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-height", "720");
            @__ctrl.HRef = "";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <i class=\"fa fa-book\" aria-hidden=\"true\"></i>\r\n            " +
                        "    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlTitleLbl() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.TitleLbl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CssClass = "col-form-label text-info fw-bold mb-1";
            @__ctrl.ID = "TitleLbl";
            @__ctrl.Text = "Düzenli Nakit Bağışçı Listesi";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlIdLbl() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.IdLbl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CssClass = "col-form-label text-white";
            @__ctrl.ID = "IdLbl";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlCardHeader() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.CardHeader = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "card-header");
            @__ctrl.ID = "CardHeader";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControlCloseBtn();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <h3 class=\"mb-2\">\r\n                "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl2;
            @__ctrl2 = this.@__BuildControlYonergeLnk();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControlTitleLbl();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControlIdLbl();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </h3>\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlAyDDL() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.AyDDL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "AyDDL";
            @__ctrl.CssClass = "form-control form-select form-select-lg fw-bold";
            @__ctrl.AutoPostBack = true;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "height: auto");
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.AyDDL_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.AyDDL_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlYilDDL() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.YilDDL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "YilDDL";
            @__ctrl.CssClass = "form-control form-select form-select-lg fw-bold";
            @__ctrl.AutoPostBack = true;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "height: auto");
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.YilDDL_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.YilDDL_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlDurumDDL() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.DurumDDL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DurumDDL";
            @__ctrl.CssClass = "form-control form-select form-select-lg fw-bold";
            @__ctrl.AutoPostBack = true;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "height: auto");
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.DurumDDL_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.DurumDDL_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlparamNakitBagisciIdLbl() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.paramNakitBagisciIdLbl = @__ctrl;
            @__ctrl.ID = "paramNakitBagisciIdLbl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("text", "Label");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "border-style: none;");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("text-align", "center");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <div class=\'loaderMainContainer\'>\r\n                        " +
                        "<div class=\'loaderContainer\'>\r\n                            <div class=\'loaderCir" +
                        "cle\'></div>\r\n                        </div>\r\n                    </div>\r\n       " +
                        "         "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.UpdateProgress @__BuildControlupdateProgress() {
            global::System.Web.UI.UpdateProgress @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdateProgress();
            this.updateProgress = @__ctrl;
            @__ctrl.ProgressTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "updateProgress";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlBagisciAdiLbl() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.BagisciAdiLbl = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "BagisciAdiLbl";
            @__ctrl.Text = "Bağışçı Bilgileri";
            @__ctrl.Font.Bold = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlModalDoldurBtn() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.ModalDoldurBtn = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ModalDoldurBtn";
            @__ctrl.CausesValidation = false;
            @__ctrl.Text = "";
            @__ctrl.Click -= new System.EventHandler(this.ModalDoldurBtn_Click);
            @__ctrl.Click += new System.EventHandler(this.ModalDoldurBtn_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control7() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Ad/Ünvan"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control8() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("TC Kimlik No"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control9() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Adres"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control10() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("İli/İlçesi"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control11() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Telefon"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderCell @__BuildControl__control12() {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderCell();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Tüzel Kişi"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControl__control6(System.Web.UI.WebControls.TableCellCollection @__ctrl) {
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control8();
            @__ctrl.Add(@__ctrl2);
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control9();
            @__ctrl.Add(@__ctrl3);
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control10();
            @__ctrl.Add(@__ctrl4);
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl5);
            global::System.Web.UI.WebControls.TableHeaderCell @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl6);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.TableHeaderRow @__BuildControl__control5() {
            global::System.Web.UI.WebControls.TableHeaderRow @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TableHeaderRow();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            this.@__BuildControl__control6(@__ctrl.Cells);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControl__control4(System.Web.UI.WebControls.TableRowCollection @__ctrl) {
            global::System.Web.UI.WebControls.TableHeaderRow @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.Table @__BuildControlBagisciTable() {
            global::System.Web.UI.WebControls.Table @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Table();
            this.BagisciTable = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CssClass = "table text-center table-bordered table-striped";
            @__ctrl.ID = "BagisciTable";
            this.@__BuildControl__control4(@__ctrl.Rows);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControlBagisBilgileriLbl() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.BagisBilgileriLbl = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "BagisBilgileriLbl";
            @__ctrl.Text = "Bağışçının Yaptığı Nakit Bağışlar";
            @__ctrl.Font.Bold = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControl__control3(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <div class=\"modal-header\">\r\n                        <h3>\r\n " +
                        "                           "));
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControlBagisciAdiLbl();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </h3>\r\n                    </div>\r\n                    " +
                        "<div class=\"modal-body\">\r\n                        <div style=\"display: none\">\r\n " +
                        "                           "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl2;
            @__ctrl2 = this.@__BuildControlModalDoldurBtn();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n\r\n                        <div class=\"m-1 text-" +
                        "center\" id=\"NakitBagisciDiv\">\r\n                            "));
            global::System.Web.UI.WebControls.Table @__ctrl3;
            @__ctrl3 = this.@__BuildControlBagisciTable();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                        <div>\r\n                " +
                        "            <h3>\r\n                                <br />\r\n                      " +
                        "          "));
            global::System.Web.UI.WebControls.Label @__ctrl4;
            @__ctrl4 = this.@__BuildControlBagisBilgileriLbl();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </h3>
                        </div>
                        <div class=""form-group"">
                            <table id=""CustomModalDataTable"" class=""table table-bordered table-striped"" width=""100%"">
                                <thead>
                                    <tr>
                                        <th>Bağış Tarihi</th>
                                        <th>Bağış Miktarı</th>
                                        <th>Banka</th>
                                        <th>Armağan</th>
                                        <th>Armağan Tutarı</th>
                                        <th>Armağan Durumu</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <div class=""modal-footer"">
                        <button type=""button"" class=""btn btn-default"" data-bs-dismiss=""modal"">Kapat</button>
                    </div>
                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control3));
            @__ctrl.ID = "UpdatePanel1";
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControlArmaganOlusturBtn() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.ArmaganOlusturBtn = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ArmaganOlusturBtn";
            @__ctrl.CausesValidation = false;
            @__ctrl.Text = "";
            @__ctrl.Click -= new System.EventHandler(this.ArmaganOlusturBtn_Click);
            @__ctrl.Click += new System.EventHandler(this.ArmaganOlusturBtn_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhdnNakitBagisciId() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hdnNakitBagisciId = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hdnNakitBagisciId";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlhdnDuzenliBagisciId() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.hdnDuzenliBagisciId = @__ctrl;
            @__ctrl.TemplateControl = this;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            @__ctrl.ID = "hdnDuzenliBagisciId";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControl__control13(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    <div class=""modal-header"">
                        <h5 class=""modal-title"" id=""onayModalLabel"">Onay</h5>
                        <button type=""button"" class=""close float-end"" data-bs-dismiss=""modal"" aria-label=""Kapat"">
                          <span aria-hidden=""true"">&times;</span>
                        </button>
                    </div>
                    <div class=""modal-body"">
                        Düzenli Bağışçı Belgesi oluşturulsun mu?

                    </div>
                    <div style=""display: none"">
                        "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            @__ctrl1 = this.@__BuildControlArmaganOlusturBtn();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl2;
            @__ctrl2 = this.@__BuildControlhdnNakitBagisciId();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl3;
            @__ctrl3 = this.@__BuildControlhdnDuzenliBagisciId();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                    </div>
                    <div class=""modal-footer"">
                        <button type=""button"" class=""btn btn-default"" data-bs-dismiss=""modal"">Kapat</button>
                        <button type=""button"" class=""btn btn-success"" id=""onaylaBtn"">Onayla</button>
                    </div>
                "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel2() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel2 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control13));
            @__ctrl.ID = "UpdatePanel2";
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__BuildControlTree(global::NBYS_WebParts.DuzenliNakitBagisciListesiWP.DuzenliNakitBagisciListesiWP @__ctrl) {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlCardHeader();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            @__ctrl2 = this.@__BuildControlAyDDL();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlYilDDL();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            @__ctrl4 = this.@__BuildControlDurumDDL();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl5;
            @__ctrl5 = this.@__BuildControlparamNakitBagisciIdLbl();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.UpdateProgress @__ctrl6;
            @__ctrl6 = this.@__BuildControlupdateProgress();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.UpdatePanel @__ctrl7;
            @__ctrl7 = this.@__BuildControlUpdatePanel1();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.UpdatePanel @__ctrl8;
            @__ctrl8 = this.@__BuildControlUpdatePanel2();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"
<script>    
    //excele export ettikten donup sonra kalmasın diye
    function setFormSubmitToFalse() {
        setTimeout(function () { _spFormOnSubmitCalled = false; }, 3000);
        return true;
    }
    function OpenModal(nakitBagisciId) {
        document.getElementById('");
                         @__w.Write( paramNakitBagisciIdLbl.ClientID);

            @__w.Write("\').value = nakitBagisciId;\r\n\r\n        var myModalInstance = bootstrap.Modal.getOr" +
                    "CreateInstance(document.getElementById(\'ModalUrlDiv\'));\r\n        myModalInstance" +
                    ".show();\r\n        document.getElementById(\'");
                         @__w.Write( ModalDoldurBtn.ClientID);

            @__w.Write(@"').click();
    }
    var selectedNakitBagisciId = null;
    var selectedDuzenliBagisciId = null;

    function showDuzenliBagisOnay(nakitBagisciId, duzenliBagisciId) {
        selectedNakitBagisciId = nakitBagisciId;
        selectedDuzenliBagisciId = duzenliBagisciId;
        $('#duzenliBagisOnayModal').modal('show');
    }

    $(document).on('click', '#onaylaBtn', function () {
        $('#duzenliBagisOnayModal').modal('hide');
        DuzenliBagisBelgesiOlustur(selectedNakitBagisciId, selectedDuzenliBagisciId);
    });

    function DuzenliBagisBelgesiOlustur(nakitBagisciId, duzenliBagisciId) {
        // Parametreleri hidden inputlara yaz
        document.getElementById('");
                         @__w.Write( hdnNakitBagisciId.ClientID );

            @__w.Write("\').value = nakitBagisciId;\r\n        document.getElementById(\'");
                         @__w.Write( hdnDuzenliBagisciId.ClientID );

            @__w.Write("\').value = duzenliBagisciId;\r\n        // Sunucu tarafı eventini tetikle\r\n        " +
                    "document.getElementById(\'");
                         @__w.Write( ArmaganOlusturBtn.ClientID );

            @__w.Write("\').click();\r\n    }\r\n</script>\r\n<style>\r\n    .table-danger {\r\n        background-c" +
                    "olor: #ffcccc !important;\r\n        font-weight: bold;\r\n        color: #a94442 !i" +
                    "mportant;\r\n    }\r\n</style>\r\n<div class=\"col-xl\">\r\n    <div class=\"card shadow\">\r" +
                    "\n        ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n        <div class=\"card-body mt-1\">\r\n            <div class=\"row m-2 \">\r\n     " +
                    "           <div class=\"form-group col-2\">\r\n                    <label class=\"for" +
                    "m-label\" for=\"AyDDL\">Başlangıç Ayı </label>\r\n                    ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                <div class=\"form-group col-2\">\r\n       " +
                    "             <label class=\"form-label\" for=\"YilDDL\">Başlangıç Yılı </label>\r\n   " +
                    "                 ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n                <div class=\"form-group col-3\">\r\n       " +
                    "             <label class=\"form-label\" for=\"DurumDDL\">Durum </label>\r\n          " +
                    "          ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                </div>\r\n            </div>\r\n            <div style=\"display: no" +
                    "ne\">\r\n                ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write(@"
            </div>
            <div class=""form-group"">
                <table id=""CustomDataTable"" class=""table table-striped small"" width=""100%"">
                    <thead>
                        <tr>
                            <th>Adı Soyadı</th>
                            <th>TCKN</th>
                            <th>Tutar</th>
                            <th>Başlama Tarihi</th>
                            <th>Telefon</th>
                            <th>Bölge</th>
                            <th>İl</th>
                            <th>İlçesi</th>
                            <th>Adres</th>
                            <th>İşlem Açıklama</th>
                            <th>Düzenli Bağış Belgesi</th>
                            <th>Bağışçı</th>
                        </tr>
                    </thead>
                </table>
            </div>
            ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write(@"
        </div>
        <div class=""card-footer"">
            
        </div>
    </div>
</div>
<div class=""modal"" id=""ModalUrlDiv"" role=""dialog"">
    <div class=""modal-dialog modal-lg"">
        <!-- Modal content-->
        <div class=""modal-content"">
            ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div class=\"modal\" id=\"duzenliBagisOnayMo" +
                    "dal\" role=\"dialog\">\r\n    <div class=\"modal-dialog\">\r\n        <!-- Modal content-" +
                    "->\r\n        <div class=\"modal-content\">\r\n            ");
            parameterContainer.Controls[7].RenderControl(@__w);
            @__w.Write("\r\n        </div>\r\n    </div>\r\n</div>");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "18.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
